import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

shell = { program = "/bin/zsh" }
live_config_reload = true

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = 'Regular' }
bold = { family = "JetBrainsMono Nerd Font", style = 'Bold' }
italic = { family = "JetBrainsMono Nerd Font", style = 'Italic' }
size = 16

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"
